default_context:
  project_name: 'cephalo-landmarks'
  project_slug: 'cephalo-landmarks'
  domain_main: 'cephalo-landmarks.com'
  domain_staging: 'stag.cephalo-landmarks.com'
  docker_swarm_stack_name_main: 'cephalo-landmarks-com'
  docker_swarm_stack_name_staging: 'stag-cephalo-landmarks-com'
  secret_key: 'Richard'
  first_superuser: 'admin@cephalo-landmarks.com'
  first_superuser_password: 'admincephalo'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.cephalo-landmarks.com", "https://stag.cephalo-landmarks.com", "https://cephalo-landmarks.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@cephalo-landmarks.com'
  postgres_password: 'admincephalo'
  pgadmin_default_user: 'admin@cephalo-landmarks.com'
  pgadmin_default_user_password: 'admincephalo'
  traefik_constraint_tag: 'cephalo-landmarks.com'
  traefik_constraint_tag_staging: 'stag.cephalo-landmarks.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admincephalo'
  sentry_dsn: 'https://c3c28509705b43e48eb1c602326ded4f@o503735.ingest.sentry.io/5589228'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
