"""Add cephalo and cephalo landamrks

Revision ID: 1276f064b13a
Revises: d4867f3a4c0a
Create Date: 2021-01-16 17:01:44.047650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1276f064b13a'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cephalo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('px_per_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cephalo_file_path'), 'cephalo', ['file_path'], unique=False)
    op.create_index(op.f('ix_cephalo_id'), 'cephalo', ['id'], unique=False)
    op.create_table('cephalo_landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landmark_number', sa.Integer(), nullable=True),
    sa.Column('landmark_x', sa.Float(), nullable=True),
    sa.Column('landmark_y', sa.Float(), nullable=True),
    sa.Column('cephalo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cephalo_id'], ['cephalo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cephalo_landmark_id'), 'cephalo_landmark', ['id'], unique=False)
    op.create_index(op.f('ix_cephalo_landmark_landmark_number'), 'cephalo_landmark', ['landmark_number'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_cephalo_landmark_landmark_number'), table_name='cephalo_landmark')
    op.drop_index(op.f('ix_cephalo_landmark_id'), table_name='cephalo_landmark')
    op.drop_table('cephalo_landmark')
    op.drop_index(op.f('ix_cephalo_id'), table_name='cephalo')
    op.drop_index(op.f('ix_cephalo_file_path'), table_name='cephalo')
    op.drop_table('cephalo')
    # ### end Alembic commands ###
